# Generated by Django 2.0.2 on 2018-07-02 19:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reviews',
            new_name='review',
        ),
    ]
