# Generated by Django 2.0.2 on 2018-07-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20180722_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentrep',
            field=models.IntegerField(default=0),
        ),
    ]
