# Generated by Django 2.0.2 on 2018-07-22 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_comment_commentrep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentrep',
        ),
    ]
