# Generated by Django 2.0.2 on 2018-07-24 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0021_auto_20180724_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='totalblogs',
            new_name='followers',
        ),
        migrations.AddField(
            model_name='topic',
            name='proposed_by',
            field=models.ForeignKey(default=1, on_delete=None, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
