# Generated by Django 2.0.2 on 2018-07-01 19:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='username',
            field=models.CharField(default=datetime.datetime(2018, 7, 1, 19, 34, 24, 393220, tzinfo=utc), max_length=150),
            preserve_default=False,
        ),
    ]
