# Generated by Django 2.0.2 on 2018-07-01 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userdetail_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='lastvisit',
        ),
    ]
