# Generated by Django 2.0.2 on 2018-07-06 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userdetail_lastseen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='lastseen',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 6, 16, 11, 16, 638177, tzinfo=utc)),
        ),
    ]
