# Generated by Django 2.0.2 on 2018-07-06 17:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180706_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='lastseen',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 6, 17, 9, 0, 153902, tzinfo=utc)),
        ),
    ]
