# Generated by Django 2.0.2 on 2018-07-06 17:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180706_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={},
        ),
        migrations.RemoveField(
            model_name='history',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='lastseen',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 6, 17, 17, 35, 10165, tzinfo=utc)),
        ),
    ]
