# Generated by Django 2.0.2 on 2018-07-07 15:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180706_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='lastseen',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 7, 15, 14, 13, 835443, tzinfo=utc)),
        ),
    ]
