# Generated by Django 2.0.2 on 2018-07-07 16:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180707_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='lastseen',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 7, 16, 46, 23, 279572, tzinfo=utc)),
        ),
    ]
