# Generated by Django 2.0.2 on 2018-07-22 11:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20180722_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='lastseen',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 11, 41, 42, 882918, tzinfo=utc)),
        ),
    ]
