# Generated by Django 2.0.2 on 2018-07-22 15:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20180722_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='lastseen',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 15, 23, 4, 287534, tzinfo=utc)),
        ),
    ]
