# Generated by Django 2.0.2 on 2018-07-22 20:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20180722_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_location),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='lastseen',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 22, 20, 5, 10, 65773, tzinfo=utc)),
        ),
    ]
