# Generated by Django 2.0.2 on 2018-07-23 18:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20180722_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='lastseen',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 23, 18, 47, 51, 632038, tzinfo=utc)),
        ),
    ]
