# Generated by Django 2.0.2 on 2018-07-23 18:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20180723_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='lastseen',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 23, 18, 50, 2, 755044, tzinfo=utc)),
        ),
    ]
