# Generated by Django 2.0.2 on 2018-07-24 09:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20180724_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='lastseen',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 24, 9, 36, 42, 445585, tzinfo=utc)),
        ),
    ]
