# Generated by Django 2.0.2 on 2018-07-24 11:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20180724_1048'),
        ('users', '0024_auto_20180724_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='interest_topics',
            field=models.ManyToManyField(to='posts.topic'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='lastseen',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 24, 11, 3, 58, 830644, tzinfo=utc)),
        ),
    ]
