# Generated by Django 2.0.2 on 2018-07-25 21:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20180724_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='lastseen',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 25, 21, 28, 6, 100081, tzinfo=utc)),
        ),
    ]
