# Generated by Django 2.0.2 on 2018-07-25 21:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20180725_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='lastseen',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 25, 21, 42, 35, 384859, tzinfo=utc)),
        ),
    ]
